services:
  clamav-hashbuilder:
    build: .
    container_name: clamav-hashbuilder
    volumes:
      - ./output:/opt/output
    restart: unless-stopped
    command: /bin/sh -c "while true; do /usr/local/bin/update_and_convert.sh; sleep 86400; done"
